apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |  
    - rolearn: arn:aws:iam::386123616643:user/gitlab-AKIAVTZWC2GB6HW5PMWD
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
